### ISSUE TITLE
HTML - multiple sections for different gym equipment focuses

### ISSUE THREAD

**Issue by strbodj** [EECE3093C/team-project-big-boys-frontend#6]

**Comment by strbodj** [comment]
Review sections covered in the UML Diagram

**Comment by strbodj** [comment]
Chest, Back, Shoulders, Legs, and admin area (settings)

**Comment by Mansonpb** [comment]
The layout of the sections is complete. The only thing that needs to be done is to connect the "Stop Light" color system from the hardware to the pages to show the status of the gym equipment.
