### ISSUE TITLE
CSS color formatting and designing page layout

### ISSUE THREAD

**Issue by strbodj** [EECE3093C/team-project-big-boys-frontend#7]

**Comment by strbodj** [comment]
CSS color palette we've used: #FFFFFF #CCCCCC #E33411 #B0341B #B8786C

**Comment by Mansonpb** [comment]
Font Style is Arial

**Comment by Mansonpb** [comment]
On the tab bar for the desktop view, it is harder to view the tab you are clicking on as you click on the tabs. We might want to change the color of the text for the tab bar as you click on them or get rid of that feature entirely

![Image](https://user-images.githubusercontent.com/123910348/228390405-03a88c37-a012-4d6d-891f-f3090e89c4ac.JPG)

.
