### ISSUE TITLE
Meeting with Parker & Devyn 3/26/2023

### ISSUE THREAD

**Issue by Mansonpb** [EECE3093C/team-project-big-boys-frontend#8]

**Comment by Mansonpb** [comment]
The meeting was on 3/26/2023 from 12 pm - 1:30 pm with Parker and Devyn to discuss and work on the website.
We started with getting a general layout and picking out a color palette. We will meet again sometime Monday to finish up the CSS Color and multiple sections of gym equipment.

**Comment by strbodj** [comment]
During this meeting, we took the time to configure our default CSS template that we could reference in our HTML code to guide us in our task to prepare the website for code integration. The remaining portions of the website that need to be complete are the different sections on the website to see the availability of specific equipment: chest, back, shoulders, etc.
